# Generated by Django 5.0.7 on 2024-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_userinfo_rename_artist_song_uploader_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', to='music.genre'),
        ),
    ]
