# Generated by Django 5.0.7 on 2024-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_user_info_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
