# Generated by Django 5.0.7 on 2024-08-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_stream_options_stream_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='music.song'),
        ),
    ]
