# Generated by Django 5.0.7 on 2024-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_playlist_image_playlistdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistdetails',
            options={'ordering': ['order'], 'verbose_name': 'playlist detail', 'verbose_name_plural': 'playlists details'},
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='artist_verified',
            field=models.BooleanField(default=False),
        ),
    ]
