# Generated by Django 5.0.7 on 2024-08-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='artist_verified',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='playlist',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlistdetails',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='music.song'),
        ),
    ]
