# Generated by Django 5.0.7 on 2024-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_rename_artist_verified_userinfo_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed_at',
        ),
        migrations.AddField(
            model_name='follow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
