# Generated by Django 5.0.7 on 2024-08-20 08:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_remove_follow_followed_at_follow_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
