# Generated by Django 5.0.7 on 2024-08-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_playlist_image_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistdetails',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='music.playlist'),
        ),
    ]
