# Generated by Django 5.0.7 on 2024-08-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_alter_playlistdetails_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
