# Generated by Django 5.0.7 on 2024-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_alter_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='playlistdetails',
            unique_together={('playlist', 'song', 'order')},
        ),
    ]
