# Generated by Django 5.0.7 on 2024-09-04 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_song_is_downloadable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='music.song')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='music.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_downloadable', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Price in VND', max_digits=10, null=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='music.song')),
            ],
        ),
    ]
