# Generated by Django 5.0.7 on 2024-09-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_purchase_songaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_downloadable',
        ),
    ]
