# Generated by Django 5.0.7 on 2024-09-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_remove_song_is_downloadable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_in_vnd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Completed'), (3, 'Failed')], default=1),
        ),
    ]
