# Generated by Django 5.0.7 on 2024-09-07 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='song',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='music.song'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
