# Generated by Django 5.0.7 on 2024-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='verb',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
