# Generated by Django 5.0.7 on 2024-09-12 14:37

import cloudinary.models
import django.db.models.deletion
import music.validate
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_notification_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='videos/', validators=[music.validate.validate_video_file])),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mv', to='music.song')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Music Video',
                'verbose_name_plural': 'Music Videos',
            },
        ),
    ]
