# Generated by Django 5.0.7 on 2024-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_musicvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='is_public',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Scheduled')], default=2),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_public',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Scheduled')], default=2),
        ),
    ]
