# Generated by Django 5.0.7 on 2024-09-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_alter_musicvideo_is_public_alter_song_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
