# Generated by Django 4.1.13 on 2024-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_musicvideo_release_date_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.genre'),
        ),
    ]
