# Generated by Django 5.1.1 on 2024-09-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_alter_livestream_stream_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestream',
            old_name='stream_file',
            new_name='file',
        ),
    ]
