# Generated by Django 5.1.1 on 2024-10-02 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_livestream_title_userinfo_is_artist_livestreamchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_artist',
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Completed'), (3, 'Failed')], default=1)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_in_vnd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_subscription', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='music.premiumsubscription')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Completed'), (3, 'Failed')], default=1)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_in_vnd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('song', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='music.song')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
