# Generated by Django 5.1.1 on 2024-10-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0039_remove_userinfo_is_artist_premiumsubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumtransaction',
            name='premium_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='music.premiumsubscription'),
        ),
    ]
