# Generated by Django 5.1.1 on 2024-10-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_alter_premiumtransaction_premium_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumtransaction',
            name='premium_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='music.premiumsubscription'),
        ),
    ]
