# Generated by Django 5.1.1 on 2024-10-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0041_alter_premiumtransaction_premium_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumtransaction',
            name='user',
        ),
    ]
