# Generated by Django 5.1.1 on 2024-10-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0042_remove_premiumtransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumsubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
