# Generated by Django 5.1.1 on 2024-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0043_alter_premiumsubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumtransaction',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
