# Generated by Django 5.1.1 on 2024-10-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0044_premiumtransaction_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title', 'artists'], name='music_song_title_29a1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['lyrics', 'description'], name='music_song_lyrics_f05a46_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(db_tablespace='fulltext', fields=['title', 'artists', 'lyrics', 'description'], name='fulltext_idx'),
        ),
    ]
