# Generated by Django 5.1.1 on 2024-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0046_alter_playlist_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
