# Generated by Django 5.1.1 on 2024-10-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0047_alter_livestream_session_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveStreamChat',
            new_name='LiveStreamComment',
        ),
    ]
