# Generated by Django 5.1.1 on 2024-10-14 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0048_rename_livestreamchat_livestreamcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mv', to='music.song'),
        ),
    ]
