# Generated by Django 5.1.1 on 2024-10-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0049_alter_musicvideo_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
